apiVersion: batch/v1
kind: CronJob
metadata:
  name: redisInfo
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: redisInfo
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - redis-cli INFO replication
          restartPolicy: OnFailure