apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-info-job
  namespace: redis
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        cron-job-name: redis-info
    spec:
      template:
        spec:
          containers:
          - name: redis-info-container
            image: redis:6.2.3-alpine
            command: ["redis-cli"]
            args:
            - "-h"
            - "redis-1.redis.redis.svc.cluster.local"
            - "-p"
            - "6379"
            - "-a"
            - "passw0rd"
            - "INFO"
            - "replication"
          restartPolicy: OnFailure