apiVersion: batch/v1
kind: CronJob
metadata:
  name: redisInfo
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: redisInfo
            image: redis:6.2.3-alpine
            imagePullPolicy: IfNotPresent
            command:
            - redis-cli -h redis-1.redis.redis.svc.cluster.local -p 6379
            - auth passw0rd
            - INFO replication
          restartPolicy: OnFailure
